// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1OyxRzvor40w3y1fUmNNR6FvM1DFoA3o',
    appId: '1:789286941266:web:270ce15e81cde0b4b6658b',
    messagingSenderId: '789286941266',
    projectId: 'ujyalonepal-a0f68',
    authDomain: 'ujyalonepal-a0f68.firebaseapp.com',
    storageBucket: 'ujyalonepal-a0f68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1uJdkIu8vWEKMyH59lfO6s7THgJ6olA',
    appId: '1:789286941266:android:f3df98676b5bd16bb6658b',
    messagingSenderId: '789286941266',
    projectId: 'ujyalonepal-a0f68',
    storageBucket: 'ujyalonepal-a0f68.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1OyxRzvor40w3y1fUmNNR6FvM1DFoA3o',
    appId: '1:789286941266:web:5fbbb35532d7da93b6658b',
    messagingSenderId: '789286941266',
    projectId: 'ujyalonepal-a0f68',
    authDomain: 'ujyalonepal-a0f68.firebaseapp.com',
    storageBucket: 'ujyalonepal-a0f68.firebasestorage.app',
  );

}